### PR TITLE
I tried fix for Python3. (Work well)

### PR DESCRIPTION
**Pull request by dlehdgud2380**
This Source was compatible for python2.  So i tried work that compatible for python3.
I am using Python 3.6.4.

* Used urllib.request
* Fixed Regular Expression part.  Because It was to occur error.
`TypeError: can't use a string pattern on a bytes-like object`
* changed long type to int (not work in python3)

And  i tried this code.
<pre><code>response = GoogleSearch().search("neptunia")
for result in response.results:
    print("Title: " + result.title + "\nURL: " + result.url)
    print("\n")</code></pre>

Result:
<pre><code>
Title: Hyperdimension Neptunia - Wikipedia
URL: https://en.wikipedia.org/wiki/Hyperdimension_Neptunia

Title: Hyperdimension Neptunia Wiki | FANDOM powered by Wikia
URL: http://neptunia.wikia.com/wiki/Hyperdimension_Neptunia_Wiki

Title: Hyperdimension Neptunia (Series) | Hyperdimension Neptunia Wiki ...
URL: http://neptunia.wikia.com/wiki/Hyperdimension_Neptunia_(Series)

Title: Hyperdimension Neptunia Re;Birth1 / 超次次元ゲイム ネプテューヌRe ...
URL: http://store.steampowered.com/app/282900/Hyperdimension_Neptunia_ReBirth1___ReBirth1__1/

Title: Hyperdimension Neptunia | Know Your Meme
URL: http://knowyourmeme.com/memes/subcultures/hyperdimension-neptunia

Title: Crunchyroll - Hyperdimension Neptunia Full episodes streaming ...
URL: http://www.crunchyroll.com/hyperdimension-neptunia

Title: Neptunia (Video Game) - TV Tropes
URL: http://tvtropes.org/pmwiki/pmwiki.php/VideoGame/Neptunia

Title: Neptunia / Characters - TV Tropes
URL: http://tvtropes.org/pmwiki/pmwiki.php/Characters/Neptunia

Title: Megadimension Neptunia VII on PS4 | Official PlayStation™Store US
URL: https://store.playstation.com/en-us/product/UP0031-CUSA03133_00-GAME000000000000

Title: Exadimension Neptunia by Trainer_Brendan (@Trainer_Brendan) on ...
URL: https://gamejolt.com/games/exadimension-neptunia/145529
</code></pre>

### CODE REVIEW

**Comment by anthonyhseb** [comment]
Hello, and thanks for suggesting a fix. I ran tox on your version and got errors in Python 2 (the Python 3 error only concerns the number of results). I can only accept pull requests that maintain Python 2 compatibility. The python 2.7 test is not even launching. Here's the tox output:

```
GLOB sdist-make: /home/anthony/source/anthonyhseb/googlesearch/setup.py
py27 inst-nodeps: /home/anthony/source/anthonyhseb/googlesearch/.tox/dist/google-search-1.0.0.zip
py27 installed: beautifulsoup4==4.6.0,google-search==1.0.0,lxml==4.1.1,pkg-resources==0.0.0
py27 runtests: PYTHONHASHSEED='190692104'
py27 runtests: commands[0] | python setup.py test
running test
running egg_info
writing requirements to google_search.egg-info/requires.txt
writing google_search.egg-info/PKG-INFO
writing top-level names to google_search.egg-info/top_level.txt
writing dependency_links to google_search.egg-info/dependency_links.txt
reading manifest file 'google_search.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no files found matching '*.jpg' under directory 'docs'
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.gif' under directory 'docs'
writing manifest file 'google_search.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    tests_require=test_requirements
  File "/home/anthony/source/anthonyhseb/googlesearch/.tox/py27/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/anthony/source/anthonyhseb/googlesearch/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/anthony/source/anthonyhseb/googlesearch/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/anthony/source/anthonyhseb/googlesearch/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_googlesearch'
ERROR: InvocationError: '/home/anthony/source/anthonyhseb/googlesearch/.tox/py27/bin/python setup.py test'
py35 inst-nodeps: /home/anthony/source/anthonyhseb/googlesearch/.tox/dist/google-search-1.0.0.zip
py35 installed: beautifulsoup4==4.6.0,google-search==1.0.0,lxml==4.1.1,pkg-resources==0.0.0
py35 runtests: PYTHONHASHSEED='190692104'
py35 runtests: commands[0] | python setup.py test
running test
running egg_info
writing top-level names to google_search.egg-info/top_level.txt
writing dependency_links to google_search.egg-info/dependency_links.txt
writing requirements to google_search.egg-info/requires.txt
writing google_search.egg-info/PKG-INFO
reading manifest file 'google_search.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no files found matching '*.jpg' under directory 'docs'
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.gif' under directory 'docs'
writing manifest file 'google_search.egg-info/SOURCES.txt'
running build_ext
test_search (tests.test_googlesearch.TestGoolgeSearch) ... /home/anthony/source/anthonyhseb/googlesearch/.tox/py35/lib/python3.5/site-packages/bs4/builder/_lxml.py:250: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  self.parser.feed(markup)
FAIL

======================================================================
FAIL: test_search (tests.test_googlesearch.TestGoolgeSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anthony/source/anthonyhseb/googlesearch/tests/test_googlesearch.py", line 14, in test_search
    self.assertTrue(response.total > 1000, "repsonse.total is way too low")
AssertionError: False is not true : repsonse.total is way too low

----------------------------------------------------------------------
Ran 1 test in 8.291s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=0 failures=1>
ERROR: InvocationError: '/home/anthony/source/anthonyhseb/googlesearch/.tox/py35/bin/python setup.py test'
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
ERROR:   py35: commands failed
```
I'll gladly pull if the tox test succeed in both python 2.7 and 3.5 (note: change tox.ini to include python 3.5 `envlist = py27,py35`)

**Comment by dlehdgud2380** [comment]
Thank you for review my full request. I will try fix for python2.

**Comment by Souyama** [comment]
Have you guys tried with `try`-`except `block? First try importing `urllib2`, in case of exception, import the python 3 ie `urllib.request` and `urllib.parse` libraries. Same goes with all the statements that produce conflicts. Like try with `urllib2.build_opener()` if that fails try `urllib.request.build_opener().` Similarly in line  37 try for `urllib.parse.quote(query)`. 

As for line 41: `soup.select(GoogleSearch.TOTAL_SELECTOR)[0].children.__next__().encode('utf-8') #for python 3. Use `int `instead of `long `in 42. (long type is decrypted in Python 3.x Honestly I don't see any good reason for using long type here, no one's gonna scrape through that large data.)

Well that's all the problems I can pick for now.

**Comment by anthonyhseb** [comment]
@Souyama thanks for your suggestions. I am sure they would work but I am currently in the middle of working on my thesis, and cannot accept any pull requests that fail the automated tests in Tox. I will apply you suggestions as soon as I have more free time if no one provides a valid pull request.

I thank everyone for their comments and tentative pull requests and apologize for not being able to accept any pull requests that fail the Travis tests.

**Comment by Souyama** [comment]
@anthonyhseb Haven't read the tox api documentation yet so I can't say whether they will accept try except blocks, but if you are going for automated testing, I think you are better off with `sys.version_info`.

As for the pull-request, your library is going through some rewrites as of yet. I am including some advanced search features in it. Which reminds me, is your code raising any EncodingError while trying to render non-Latin characters?

Also whenever you are free will you consider documenting your library? Sometimes it's difficult to understand your code.

Will create a pull-request after my library passes this Tox test.

**Pull request closed without merging**
